/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controle.ControleMetodos;
import controle.TextPrompt;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Power Arts
 */
public class ConfigurarBanco extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ConfigurarBanco() {
        initComponents();
        TextPrompt usuario = new TextPrompt("USUÁRIO", cp_usuario);
        TextPrompt senha = new TextPrompt("SENHA", cp_senha);
        TextPrompt banco = new TextPrompt("BANCO", cp_banco);
        TextPrompt servidor = new TextPrompt("IP SERVIDOR", cp_servidor);
        iconeTitulo();
        perguntarSair();
    }

    public void iconeTitulo() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image imagem = kit.getImage(getClass().getResource("/imagens/principal/logomenor.png"));
        setIconImage(imagem);
    }

    public void perguntarSair() {
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente encerrar a aplicação?", "AVISO", YES_NO_OPTION, QUESTION_MESSAGE);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        System.exit(0);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cp_servidor = new javax.swing.JTextField();
        cp_banco = new javax.swing.JTextField();
        cp_usuario = new javax.swing.JTextField();
        cp_senha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bt_entrar = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDV - Configurar Banco de Dados");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/bancodedados.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/bancoconfig.png"))); // NOI18N
        jPanel3.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(450, 130));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cp_servidor.setBackground(new java.awt.Color(42, 102, 142));
        cp_servidor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cp_servidor.setForeground(new java.awt.Color(255, 255, 255));
        cp_servidor.setBorder(null);
        cp_servidor.setCaretColor(new java.awt.Color(255, 255, 255));
        cp_servidor.setOpaque(false);
        cp_servidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cp_servidorKeyTyped(evt);
            }
        });
        jPanel4.add(cp_servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        cp_banco.setBackground(new java.awt.Color(42, 102, 142));
        cp_banco.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cp_banco.setForeground(new java.awt.Color(255, 255, 255));
        cp_banco.setBorder(null);
        cp_banco.setCaretColor(new java.awt.Color(255, 255, 255));
        cp_banco.setOpaque(false);
        cp_banco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cp_bancoKeyTyped(evt);
            }
        });
        jPanel4.add(cp_banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        cp_usuario.setBackground(new java.awt.Color(42, 102, 142));
        cp_usuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cp_usuario.setForeground(new java.awt.Color(255, 255, 255));
        cp_usuario.setBorder(null);
        cp_usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        cp_usuario.setOpaque(false);
        cp_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cp_usuarioKeyTyped(evt);
            }
        });
        jPanel4.add(cp_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 30));

        cp_senha.setBackground(new java.awt.Color(42, 102, 142));
        cp_senha.setForeground(new java.awt.Color(255, 255, 255));
        cp_senha.setBorder(null);
        jPanel4.add(cp_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/servidor.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginPass.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginUs.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/nomebanco.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 70));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 13);
        flowLayout1.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout1);

        bt_entrar.setBackground(new java.awt.Color(42, 102, 142));
        bt_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar2.png"))); // NOI18N
        bt_entrar.setBorder(null);
        bt_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_entrar.setOpaque(false);
        bt_entrar.setPreferredSize(new java.awt.Dimension(135, 45));
        bt_entrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar1.png"))); // NOI18N
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        jPanel5.add(bt_entrar);

        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair2.png"))); // NOI18N
        bt_sair.setBorder(null);
        bt_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_sair.setOpaque(false);
        bt_sair.setPreferredSize(new java.awt.Dimension(135, 45));
        bt_sair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair1.png"))); // NOI18N
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        jPanel5.add(bt_sair);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cp_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cp_usuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_usuarioKeyTyped

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed

        String usuario = cp_usuario.getText();
        String senha = new String(cp_senha.getPassword());
        String banco = cp_banco.getText();
        String servidor = cp_servidor.getText();

        try {
            controleMetodos.gravarXML(usuario, senha, banco, servidor);
            new SplashScreen().setVisible(true);
            dispose();
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            System.out.println("Erro ao conectar ao banco");
        }

    }//GEN-LAST:event_bt_entrarActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_sairActionPerformed

    private void cp_bancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cp_bancoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_bancoKeyTyped

    private void cp_servidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cp_servidorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_servidorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigurarBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_sair;
    private javax.swing.JTextField cp_banco;
    private javax.swing.JPasswordField cp_senha;
    private javax.swing.JTextField cp_servidor;
    private javax.swing.JTextField cp_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    ControleMetodos controleMetodos = new ControleMetodos();
}
