/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas;

import produtos.*;
import bancodedados.BancoProdutos;
import controle.EstiloTabelaHeader;
import controle.EstiloTabelaRenderer;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Power Arts
 */
public class FrmFormaPag extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProdutos
     */
    public FrmFormaPag() {
        initComponents();
    }

    public void calcularTabelaCaixa() {
        String valorTabelaCaixa;
        String quantidadeTabelaCaixa;
        double total = 0;
        double valorConvertido;
        int quantidadeConvertido;
        double calc = 0.0;

        for (int i = 0; i < vendas.FrmCaixa.tabelaCaixa.getRowCount(); i++) {
            valorTabelaCaixa = vendas.FrmCaixa.tabelaCaixa.getValueAt(i, 3).toString();
            quantidadeTabelaCaixa = vendas.FrmCaixa.tabelaCaixa.getValueAt(i, 4).toString();
            valorConvertido = Double.parseDouble(valorTabelaCaixa.replace(",", "."));
            quantidadeConvertido = Integer.parseInt(quantidadeTabelaCaixa);
            calc = valorConvertido * quantidadeConvertido;
            total = total + calc;
            vendas.FrmCaixa.tabelaCaixa.setValueAt(String.format("%.2f", Math.rint(calc * 100) / 100), i, 5);
        }
        
        vendas.FrmCaixa.cp_total.setText(String.format("%.2f", Math.rint(total * 100) / 100));
        
    }

    public static boolean isNumber(String n) {
        try {
            if (Integer.parseInt(n) > 0) {
                return true;
            } else {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gp_formaPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bt_sair = new javax.swing.JButton();
        bt_calcular = new javax.swing.JButton();
        bt_finalizarPagamento = new javax.swing.JButton();
        lb_informacoesPagamento = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cp_tipo2 = new org.bolivia.combo.SComboBoxBlue();
        cp_recebido2 = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        cp_avista = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        cp_tipo3 = new org.bolivia.combo.SComboBoxBlue();
        cp_recebido3 = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        cp_tipo1 = new org.bolivia.combo.SComboBoxBlue();
        cp_parcelado = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Pagamento");
        setPreferredSize(new java.awt.Dimension(769, 493));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "INFORMAÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(735, 142));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES"));
        jPanel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setRequestFocusEnabled(false);

        bt_sair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/sair2.png"))); // NOI18N
        bt_sair.setText("Sair");
        bt_sair.setBorder(null);
        bt_sair.setContentAreaFilled(false);
        bt_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/sair1.png"))); // NOI18N
        bt_sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        bt_calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/calcularpagamento2.png"))); // NOI18N
        bt_calcular.setText("Calcular");
        bt_calcular.setBorder(null);
        bt_calcular.setContentAreaFilled(false);
        bt_calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_calcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_calcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/calcularpagamento1.png"))); // NOI18N
        bt_calcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });

        bt_finalizarPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_finalizarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/finalizarpagamento2.png"))); // NOI18N
        bt_finalizarPagamento.setText("Finalizar Pagamento");
        bt_finalizarPagamento.setBorder(null);
        bt_finalizarPagamento.setContentAreaFilled(false);
        bt_finalizarPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_finalizarPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_finalizarPagamento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/finalizarpagamento1.png"))); // NOI18N
        bt_finalizarPagamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_finalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_finalizarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(bt_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(bt_finalizarPagamento)
                .addGap(121, 121, 121)
                .addComponent(bt_sair)
                .addGap(81, 81, 81))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_calcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_finalizarPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 700, 130));

        lb_informacoesPagamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_informacoesPagamento.setForeground(new java.awt.Color(255, 0, 0));
        lb_informacoesPagamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_informacoesPagamento.setText("Informações do Pagamento");
        lb_informacoesPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lb_informacoesPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 680, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "A VISTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(735, 142));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cp_tipo2.setMaximumRowCount(5);
        cp_tipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FORMA DE PAGAMENTO", "Dinheiro", "Cartão de Crédito", "Cartão de Débito" }));
        cp_tipo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cp_tipo2.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.add(cp_tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 50));

        cp_recebido2.setBackground(new java.awt.Color(34, 102, 145));
        cp_recebido2.setBorder(null);
        cp_recebido2.setForeground(new java.awt.Color(255, 255, 255));
        cp_recebido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_recebido2.setOpaque(false);
        cp_recebido2.setPhColor(new java.awt.Color(255, 255, 255));
        cp_recebido2.setPlaceholder("VALOR");
        cp_recebido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_recebido2ActionPerformed(evt);
            }
        });
        jPanel4.add(cp_recebido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/recibi.png"))); // NOI18N
        jLabel10.setOpaque(true);
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        gp_formaPagamento.add(cp_avista);
        cp_avista.setContentAreaFilled(false);
        cp_avista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cp_avista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cp_avista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cp_avista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 50, 50));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PARCELADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(735, 142));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cp_tipo3.setMaximumRowCount(5);
        cp_tipo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FORMA DE PAGAMENTO", "Dinheiro", "Cartão de Crédito", "Cartão de Débito" }));
        cp_tipo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cp_tipo3.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel5.add(cp_tipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 50));

        cp_recebido3.setBackground(new java.awt.Color(34, 102, 145));
        cp_recebido3.setBorder(null);
        cp_recebido3.setForeground(new java.awt.Color(255, 255, 255));
        cp_recebido3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cp_recebido3.setOpaque(false);
        cp_recebido3.setPhColor(new java.awt.Color(255, 255, 255));
        cp_recebido3.setPlaceholder("ENTRADA");
        cp_recebido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_recebido3ActionPerformed(evt);
            }
        });
        jPanel5.add(cp_recebido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/recibi.png"))); // NOI18N
        jLabel11.setOpaque(true);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        cp_tipo1.setMaximumRowCount(5);
        cp_tipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PARCELAS", "1 + 1X", "1 + 2X", "1 + 3X", "1 + 4X", "1 + 5X", "1 + 6X", "1 + 7X", "1 + 8X", "1 + 9X", "1 + 10X", "1 + 11X" }));
        cp_tipo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cp_tipo1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel5.add(cp_tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 181, -1));

        gp_formaPagamento.add(cp_parcelado);
        cp_parcelado.setContentAreaFilled(false);
        cp_parcelado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cp_parcelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cp_parcelado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(cp_parcelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cp_recebido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_recebido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_recebido2ActionPerformed

    private void cp_recebido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_recebido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_recebido3ActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        
        if(cp_avista.isSelected()){
            lb_informacoesPagamento.setText("Pagamento Avista");
        }else if(cp_parcelado.isSelected()){
            lb_informacoesPagamento.setText("Pagamento Parcelado");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor, informe se o pagamento será AVISTA ou PARCELADO.");
        }
        
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_finalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_finalizarPagamentoActionPerformed
        
    }//GEN-LAST:event_bt_finalizarPagamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_finalizarPagamento;
    private javax.swing.JButton bt_sair;
    private javax.swing.JRadioButton cp_avista;
    private javax.swing.JRadioButton cp_parcelado;
    public static app.bolivia.swing.JCTextField cp_recebido2;
    public static app.bolivia.swing.JCTextField cp_recebido3;
    private org.bolivia.combo.SComboBoxBlue cp_tipo1;
    private org.bolivia.combo.SComboBoxBlue cp_tipo2;
    private org.bolivia.combo.SComboBoxBlue cp_tipo3;
    private javax.swing.ButtonGroup gp_formaPagamento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lb_informacoesPagamento;
    // End of variables declaration//GEN-END:variables
}
